/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Agent-Prism theme colors
        agentprism: {
          background: "oklch(var(--agentprism-background) / <alpha-value>)",
          foreground: "oklch(var(--agentprism-foreground) / <alpha-value>)",
          primary: "oklch(var(--agentprism-primary) / <alpha-value>)",
          "primary-foreground": "oklch(var(--agentprism-primary-foreground) / <alpha-value>)",
          secondary: "oklch(var(--agentprism-secondary) / <alpha-value>)",
          "secondary-foreground": "oklch(var(--agentprism-secondary-foreground) / <alpha-value>)",
          muted: "oklch(var(--agentprism-muted) / <alpha-value>)",
          "muted-foreground": "oklch(var(--agentprism-muted-foreground) / <alpha-value>)",
          accent: "oklch(var(--agentprism-accent) / <alpha-value>)",
          "accent-foreground": "oklch(var(--agentprism-accent-foreground) / <alpha-value>)",
          border: "oklch(var(--agentprism-border) / <alpha-value>)",
          "border-subtle": "oklch(var(--agentprism-border-subtle) / <alpha-value>)",
          "border-strong": "oklch(var(--agentprism-border-strong) / <alpha-value>)",
          "border-inverse": "oklch(var(--agentprism-border-inverse) / <alpha-value>)",
          success: "oklch(var(--agentprism-success) / <alpha-value>)",
          "success-muted": "oklch(var(--agentprism-success-muted) / <alpha-value>)",
          "success-muted-foreground": "oklch(var(--agentprism-success-muted-foreground) / <alpha-value>)",
          error: "oklch(var(--agentprism-error) / <alpha-value>)",
          "error-muted": "oklch(var(--agentprism-error-muted) / <alpha-value>)",
          "error-muted-foreground": "oklch(var(--agentprism-error-muted-foreground) / <alpha-value>)",
          warning: "oklch(var(--agentprism-warning) / <alpha-value>)",
          "warning-muted": "oklch(var(--agentprism-warning-muted) / <alpha-value>)",
          "warning-muted-foreground": "oklch(var(--agentprism-warning-muted-foreground) / <alpha-value>)",
          pending: "oklch(var(--agentprism-pending) / <alpha-value>)",
          "pending-muted": "oklch(var(--agentprism-pending-muted) / <alpha-value>)",
          "pending-muted-foreground": "oklch(var(--agentprism-pending-muted-foreground) / <alpha-value>)",
          // Timeline colors
          "timeline-llm": "oklch(var(--agentprism-timeline-llm) / <alpha-value>)",
          "timeline-agent": "oklch(var(--agentprism-timeline-agent) / <alpha-value>)",
          "timeline-tool": "oklch(var(--agentprism-timeline-tool) / <alpha-value>)",
          "timeline-chain": "oklch(var(--agentprism-timeline-chain) / <alpha-value>)",
          "timeline-retrieval": "oklch(var(--agentprism-timeline-retrieval) / <alpha-value>)",
          "timeline-embedding": "oklch(var(--agentprism-timeline-embedding) / <alpha-value>)",
          "timeline-guardrail": "oklch(var(--agentprism-timeline-guardrail) / <alpha-value>)",
          "timeline-create-agent": "oklch(var(--agentprism-timeline-create-agent) / <alpha-value>)",
          "timeline-span": "oklch(var(--agentprism-timeline-span) / <alpha-value>)",
          "timeline-event": "oklch(var(--agentprism-timeline-event) / <alpha-value>)",
          "timeline-unknown": "oklch(var(--agentprism-timeline-unknown) / <alpha-value>)",
          // Badge colors
          "badge-llm": "oklch(var(--agentprism-badge-llm) / <alpha-value>)",
          "badge-llm-foreground": "oklch(var(--agentprism-badge-llm-foreground) / <alpha-value>)",
          "badge-agent": "oklch(var(--agentprism-badge-agent) / <alpha-value>)",
          "badge-agent-foreground": "oklch(var(--agentprism-badge-agent-foreground) / <alpha-value>)",
          "badge-tool": "oklch(var(--agentprism-badge-tool) / <alpha-value>)",
          "badge-tool-foreground": "oklch(var(--agentprism-badge-tool-foreground) / <alpha-value>)",
          "badge-chain": "oklch(var(--agentprism-badge-chain) / <alpha-value>)",
          "badge-chain-foreground": "oklch(var(--agentprism-badge-chain-foreground) / <alpha-value>)",
          "badge-retrieval": "oklch(var(--agentprism-badge-retrieval) / <alpha-value>)",
          "badge-retrieval-foreground": "oklch(var(--agentprism-badge-retrieval-foreground) / <alpha-value>)",
          "badge-embedding": "oklch(var(--agentprism-badge-embedding) / <alpha-value>)",
          "badge-embedding-foreground": "oklch(var(--agentprism-badge-embedding-foreground) / <alpha-value>)",
          "badge-guardrail": "oklch(var(--agentprism-badge-guardrail) / <alpha-value>)",
          "badge-guardrail-foreground": "oklch(var(--agentprism-badge-guardrail-foreground) / <alpha-value>)",
          "badge-create-agent": "oklch(var(--agentprism-badge-create-agent) / <alpha-value>)",
          "badge-create-agent-foreground": "oklch(var(--agentprism-badge-create-agent-foreground) / <alpha-value>)",
          "badge-span": "oklch(var(--agentprism-badge-span) / <alpha-value>)",
          "badge-span-foreground": "oklch(var(--agentprism-badge-span-foreground) / <alpha-value>)",
          "badge-event": "oklch(var(--agentprism-badge-event) / <alpha-value>)",
          "badge-event-foreground": "oklch(var(--agentprism-badge-event-foreground) / <alpha-value>)",
          "badge-unknown": "oklch(var(--agentprism-badge-unknown) / <alpha-value>)",
          "badge-unknown-foreground": "oklch(var(--agentprism-badge-unknown-foreground) / <alpha-value>)",
          "badge-default": "oklch(var(--agentprism-badge-default) / <alpha-value>)",
          "badge-default-foreground": "oklch(var(--agentprism-badge-default-foreground) / <alpha-value>)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

